language: php

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

sudo: true

php:
  - 7.1

env:
  global:
    - ES_VERSION="5.x"
    - ES_TEST_HOST=http://localhost:9200
    - JAVA_HOME="/usr/lib/jvm/java-8-oracle/jre"

before_install:
  - sudo update-java-alternatives -s java-8-oracle
  - ./travis/download_and_run_es.sh
  - sleep 10

script:
  - curl localhost:9200
